version: "3"
services:
  hello-world-app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: hello-world-app
      ports:
       - "80:80"
       - "443:443"
        
